version: '3'

tasks:
  format:
    desc: "run isort and black"
    cmds:
      - isort src
      - isort tests
      - black src
      - black tests
  mypy:
    desc: "type check code"
    cmds:
      - mypy src
  lint:
    desc: "run flake 8, isort check and black check"
    cmds:
      - isort --check src
      - isort --check tests
      - black --check src
      - black --check tests
      - flake8 src
      - flake8 tests
  scan:
    desc: "Run xenon"
    cmds:
      - xenon -b B -m A -a A src/
  test:
    desc: "run pytest"
    cmds:
      - pytest .
  full-check:
    desc: "run a full code quality check"
    cmds:
      - task: lint
      - task: mypy
      - task: scan
      - task: test