name: pre-merge
on:
  pull_request:
    branches:
      - main

jobs:
  bumpver:
    name: Bump the version
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Task
        uses: arduino/setup-task@v1
      - run: task ci:install
      - run: bumpver update

  lint:
    name: Lint, Type Check and Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Task
        uses: arduino/setup-task@v1
      - run: task ci:install
      - run: task ci:lint
      - run: task ci:mypy
      - run: task ci:scan
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Task
        uses: arduino/setup-task@v1
      - run: task ci:install
      - run: task ci:test
